/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.AgendaController;
import java.awt.HeadlessException;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Pichau
 */
public class agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form agenda
     */
    public agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        box_serviço = new javax.swing.JComboBox<>();
        box_cliente = new javax.swing.JComboBox<>();
        hora_tx = new javax.swing.JTextField();
        data_tx = new javax.swing.JTextField();
        campovalor = new javax.swing.JTextField();
        id_tx = new javax.swing.JTextField();
        hora_lab = new javax.swing.JLabel();
        data_lab = new javax.swing.JLabel();
        valor_lab = new javax.swing.JLabel();
        servico_lab = new javax.swing.JLabel();
        cliente_lab = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        agenda_titulo_lab = new javax.swing.JLabel();
        bt_agendar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "cliente", "servico", "data", "hora", "valor", "opservação"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 1040, 260));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Agendar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 530, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 530, 390));

        box_serviço.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                box_serviçoItemStateChanged(evt);
            }
        });
        box_serviço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_serviçoActionPerformed(evt);
            }
        });
        getContentPane().add(box_serviço, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 290, -1));

        box_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(box_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 266, 290, 30));

        hora_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_txActionPerformed(evt);
            }
        });
        getContentPane().add(hora_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 290, -1));

        data_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_txActionPerformed(evt);
            }
        });
        getContentPane().add(data_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 290, -1));

        campovalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campovalorActionPerformed(evt);
            }
        });
        getContentPane().add(campovalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 290, -1));

        id_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txActionPerformed(evt);
            }
        });
        getContentPane().add(id_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 290, -1));

        hora_lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hora_lab.setForeground(new java.awt.Color(255, 255, 255));
        hora_lab.setText("hora");
        getContentPane().add(hora_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 100, -1));

        data_lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        data_lab.setForeground(new java.awt.Color(255, 255, 255));
        data_lab.setText("data");
        getContentPane().add(data_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 100, -1));

        valor_lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor_lab.setForeground(new java.awt.Color(255, 255, 255));
        valor_lab.setText("Valor");
        getContentPane().add(valor_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 100, -1));

        servico_lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        servico_lab.setForeground(new java.awt.Color(255, 255, 255));
        servico_lab.setText("serviço");
        getContentPane().add(servico_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 100, -1));

        cliente_lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cliente_lab.setForeground(new java.awt.Color(255, 255, 255));
        cliente_lab.setText("cliente");
        getContentPane().add(cliente_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 100, -1));

        id_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_label.setForeground(new java.awt.Color(255, 255, 255));
        id_label.setText("id ");
        getContentPane().add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));

        agenda_titulo_lab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agenda_titulo_lab.setForeground(new java.awt.Color(255, 255, 255));
        agenda_titulo_lab.setText("Agenda");
        getContentPane().add(agenda_titulo_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 180, -1));

        bt_agendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(bt_agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1300, 860));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 1370, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txActionPerformed

    private void campovalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campovalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campovalorActionPerformed

    private void data_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_txActionPerformed

    private void hora_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_txActionPerformed

    private void box_serviçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_serviçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_serviçoActionPerformed

    private void box_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_clienteActionPerformed

    private void box_serviçoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_box_serviçoItemStateChanged
        // TODO add your handling code here:
        this.controller.atualizaValor();
        
    }//GEN-LAST:event_box_serviçoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controller.agendar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agenda_titulo_lab;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> box_cliente;
    private javax.swing.JComboBox<String> box_serviço;
    private javax.swing.JLabel bt_agendar;
    private javax.swing.JTextField campovalor;
    private javax.swing.JLabel cliente_lab;
    private javax.swing.JLabel data_lab;
    private javax.swing.JTextField data_tx;
    private javax.swing.JLabel hora_lab;
    private javax.swing.JTextField hora_tx;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_tx;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel servico_lab;
    private javax.swing.JLabel valor_lab;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizaValor();
    
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JComboBox<String> getBox_cliente() {
        return box_cliente;
    }

    public void setBox_cliente(JComboBox<String> box_cliente) {
        this.box_cliente = box_cliente;
    }

    public JComboBox<String> getBox_serviço() {
        return box_serviço;
    }

    public void setBox_serviço(JComboBox<String> box_serviço) {
        this.box_serviço = box_serviço;
    }

    public JTextField getCampovalor() {
        return campovalor;
    }

    public void setCampovalor(JTextField campovalor) {
        this.campovalor = campovalor;
    }

    public JTextField getData_tx() {
        return data_tx;
    }

    public void setData_tx(JTextField data_tx) {
        this.data_tx = data_tx;
    }

    public JTextField getHora_tx() {
        return hora_tx;
    }

    public void setHora_tx(JTextField hora_tx) {
        this.hora_tx = hora_tx;
    }

    public JTextField getId_tx() {
        return id_tx;
    }

    public void setId_tx(JTextField id_tx) {
        this.id_tx = id_tx;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    
    

 
}
